name: Check JSON-LD Graph

on:
  workflow_run:
      workflows: 'Deploy static content to Pages'
      types: 'completed'
      branches:
          - 'production'

jobs:
  check-graph:
    runs-on: ubuntu-latest  # Specify the machine type
      
    steps:
    
    # - name: Checkout Code
    #   uses: actions/checkout@v4
    #   with:
    #     fetch-depth: 0

    # - name: Ensure the JSON-LD files are functional
    #   id: check-graph
    #   uses: WCRP-CMIP/CMIPLD/actions/check-graph@main

  
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Set GitHub Pages URL
        id: set-url
        run: |
          PAGES_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "PAGES_URL=$PAGES_URL" >> $GITHUB_ENV
        shell: bash

      - name: Install jsonld CLI
        run: |
          npm install -g git+https://github.com/digitalbazaar/jsonld-cli.git
        shell: bash

      - name: Validate JSON-LD from URL
        run: |
          jsonld lint "$PAGES_URL/graph.jsonld" || exit 1
        shell: bash


