name: New Issue Processing

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: write
  id-token: write
  pull-requests: write

# concurrency:
#   group: "pages"
#   cancel-in-progress: true

jobs:
  # Specify the machine type
  new-issue:
    runs-on: ubuntu-latest  # Added missing runs-on field

    steps:
      - name: Run the parser on a new issue
        id: new-issue-action
        uses: WCRP-CMIP/CMIPLD/actions/new-issue@main
