name: 'Add/Modify: Activity'
description: 'Type: activity'
title: 'Add/Modify: Activity: <enter item name>'
labels:
- delta
- activity
body:
-   type: markdown
    attributes:
        value: " To add a new activity please fill in the form below. \n\n Existing\
            \ entries are: \n\n\t  | aerchemmip | c4mip | cfmip | cmip | damip | dcpp\
            \ | geomip | lesfmip | lmip | pmip | ramip | rfmip | scenariomip | tipmip\
            \ |  \n ___ \n Alternatively [see here](https://github.com/wcrp-cmip/WCRP-universe/tree/main/src-data/activity/)\
            \ for more examples. \n  ___"
-   id: description
    attributes:
        label: Description
        description: A detailed description of the activity or project.
    validations:
        required: true
    type: input
-   id: name
    attributes:
        label: Name
        description: The name of the activity.
    validations:
        required: true
    type: input
-   id: url
    attributes:
        label: Url
        description: A URL providing further documentation or references.
    validations:
        required: true
    type: input
