name: 'Add/Modify: Realm'
description: 'Type: realm'
title: 'Add/Modify: Realm: <enter item name>'
labels:
- delta
- realm
body:
-   type: markdown
    attributes:
        value: " To add a new realm please fill in the form below. \n\n Existing entries\
            \ are: \n\n\t  | aerosol | atmos | atmoschem | land | landice | ocean\
            \ | ocnbgchem | seaice |  \n ___ \n Alternatively [see here](https://github.com/wcrp-cmip/WCRP-universe/tree/main/src-data/realm/)\
            \ for more examples. \n  ___"
-   id: description
    attributes:
        label: Description
        description: A detailed description of the realm .
    validations:
        required: true
    type: input
-   id: name
    attributes:
        label: Name
        description: CMIP name used by the realm.
    validations:
        required: true
    type: input
