name: 'Add/Modify: Consortium'
description: 'Type: consortium'
title: 'Add/Modify: Consortium: <enter item name>'
labels:
- delta
- consortium
body:
-   type: markdown
    attributes:
        value: Please fill in the form below.
-   id: '@context'
    attributes:
        label: '@Context'
        description: Context identifier, typically set to '_context_'
    validations:
        required: true
    type: input
-   id: changes
    attributes:
        label: Changes
        description: Description of recent changes to the consortia
    validations:
        required: false
    type: input
-   id: cmip-acronym
    attributes:
        label: Cmip-Acronym
        description: Official acronym for the consortia
    validations:
        required: true
    type: input
-   id: members
    attributes:
        label: Members
        description: Map of member organizations within the consortia
    validations:
        required: true
    type: input
-   id: name
    attributes:
        label: Name
        description: Full name of the consortia
    validations:
        required: true
    type: input
-   id: status
    attributes:
        label: Status
        description: Current operational status of the consortia
        options:
        - active
        - inactive
        - dissolved
    validations:
        required: true
    type: dropdown
-   id: url
    attributes:
        label: Url
        description: Official website or reference URL
    validations:
        required: false
    type: input
