name: 'Add: Institution'
description: 'Type: Institution'
title: 'Add: Institution: <Type Institution Acronym Here>'
labels:
    - alpha
    - institution
body:



-   type: markdown
    attributes:
        value: |
            ####
            ## Adding a new Institution. 

            Please fill in the information below. 
            
-   type: dropdown
    id: category
    attributes:
        label: "Issue Type"
        #   description: "This is pre-set and cannot be changed."
        options:
            - "institution"
        default: 0
    validations:
        required: true


-   id: label
    attributes:
        label: Acronym
        description: |
            A short acronym from which your institution can be identified with. 
            
            Note: This name must be unique across all organisations and cannot be changed once data is published with it.
        placeholder: 'e.g., UoYork, MOHC, CMIP-IPO'
    validations:
        required: true
    type: input
-   id: long_label
    attributes:
        label: Full name of the organisation. 
        description: |
            Please provide a full name for the organisation, namely to perform a series of checks, and allow users to better understand the acronym above. 
        placeholder: 'e.g. University of York (UK)'
    validations:
        required: true
    type: input
-   id: description
    attributes:
        label: ROR
        description: |
            To help maintain traceability we are making use of the research organisation registry (ROR). 
            This allows us to generate a unique id for each institution and thus extract a detailed log of an organisations history. 

            To get your organisation ROR number, visit [ror.org](ror.org) and use the search. In the case where your specific organisation has not been registered, please do so using the form on the website, and fill this form out afterwards. 

            In the case where an open request is created on ROR, but a number has not yet been issued, please paste the reference url to the issue in this field instead. 
        placeholder: 'e.g. 04m01e293'
    validations:
        required: true
    type: input
-   id: notes
    attributes:
        label: Other Notes
        description: |
            
            Generally this section will remain empty, however additional notes (e.g. source_id submissions using this institution) can be referenced here.  
    validations:
        required: false
    type: textarea
