name: "Add/Modify: Consortium"
description: Add or modify a consortium (group of institutions) in WCRP Universe
title: "Add/Modify: Consortium: <Type consortium name here>"
labels: ['delta', 'organisation', 'consortium', 'Review', 'keep-open']
body:
  - type: markdown
    attributes:
      value: |
        ## Add/Modify: Consortium
        
        A consortium is a group of institutions working together. Select the member institutions below.

  - type: input
    id: validation_key
    attributes:
      label: Consortium Name
      description: Unique identifier for the consortium (lowercase)
      placeholder: "e.g. cmip-ipo"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full display name of the consortium
      placeholder: "e.g. CMIP International Project Office"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the consortium and its purpose

  - type: input
    id: url
    attributes:
      label: URL
      description: Website or reference URL for the consortium
      placeholder: "e.g. https://wcrp-cmip.org"

  - type: checkboxes
    id: institutions
    attributes:
      label: Member Institutions
      description: |
        Select all institutions that are members of this consortium. You may select more than one.
    validations:
      required: true

  - type: input
    id: other_institutions
    attributes:
      label: Other Institutions
      description: |
        If member institutions are not listed above enter their names here (comma-separated). These institutions should be registered first.
      placeholder: "e.g. Institution A; Institution B"

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: collaborators
    attributes:
      label: Additional Collaborators
      description: |
        To add attribution to additional members include their GitHub usernames (only) separated by a comma.
      placeholder: "e.g. user1"
      default:  user3
