name: 'General Issue'
description: 'Report a general issue, bug, or request'
title: 'Issue: <Brief description here>'
projects: ["WCRP-CMIP/4"]  # WCRP-universe CVs project
labels:
    - universal
    - general
body:

-   type: markdown
    attributes:
        value: |
            ## General Issue Report

            Please provide details about your issue, bug report, or feature request.

-   id: issue_type
    attributes:
        label: Issue Type
        description: What kind of issue are you reporting?
        options:
            - Bug Report
            - Feature Request
            - Documentation Issue
            - Data Quality Issue
            - Process Improvement
            - Other
    validations:
        required: true
    type: dropdown

-   id: affected_areas
    attributes:
        label: Affected Areas
        description: |
            Which parts of WCRP-universe does this issue affect?
            
            *Select multiple if applicable*
        options:
            - Controlled Vocabularies (CVs)
            - Documentation
            - GitHub Actions/Workflows
            - Data Files
            - Scripts/Tools
            - Issue Templates
            - General Repository Structure
            - All/Multiple Areas
        multiple: true
    validations:
        required: true
    type: dropdown

-   id: description
    attributes:
        label: Description
        description: |
            Provide a clear and detailed description of the issue.
            
            For bugs: What happened? What did you expect to happen?
            For features: What would you like to see added/changed?
        placeholder: |
            Describe your issue in detail...
            
            Include any relevant context, examples, or use cases.
    validations:
        required: true
    type: textarea

-   id: current_behavior
    attributes:
        label: Current Behavior
        description: |
            If reporting a bug or suggesting an improvement, describe the current behavior.
        placeholder: 'Currently, the system does...'
    validations:
        required: false
    type: textarea

-   id: expected_behavior
    attributes:
        label: Expected/Desired Behavior
        description: |
            What should happen instead? What would you like to see?
        placeholder: 'The system should...'
    validations:
        required: false
    type: textarea

-   id: steps_to_reproduce
    attributes:
        label: Steps to Reproduce (for bugs)
        description: |
            If reporting a bug, provide step-by-step instructions to reproduce the issue.
        placeholder: |
            1. Go to...
            2. Click on...
            3. See error...
        render: markdown
    validations:
        required: false
    type: textarea

-   id: possible_solution
    attributes:
        label: Possible Solution
        description: |
            If you have ideas on how to fix or implement this, please share them.
        placeholder: 'One possible approach could be...'
    validations:
        required: false
    type: textarea

-   id: additional_context
    attributes:
        label: Additional Context
        description: |
            Add any other context, screenshots, error messages, or relevant information.
            
            You can paste error logs, attach images, or provide links to related issues.
        placeholder: 'Any additional information...'
    validations:
        required: false
    type: textarea

-   type: markdown
    attributes:
        value: |
            ## Metadata

-   id: priority
    type: dropdown
    attributes:
        label: Priority
        description: How urgent is this issue?
        options:
            - "Critical - Blocking work"
            - "High - Important issue"
            - "Medium - Should be addressed"
            - "Low - Nice to fix"
        default: 2
    validations:
        required: true

-   id: help_needed
    type: checkboxes
    attributes:
        label: Help Needed
        description: Do you need help with this issue?
        options:
            - label: "I can work on this myself"
            - label: "I need help implementing a solution"
            - label: "I'm just reporting this issue"
    validations:
        required: false
