name: "Add/Modify: Region"
description: Add or modify a region in WCRP Universe
title: "Add/Modify: Region: <Type name here>"
labels: ['delta', 'region', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Add/Modify: Region
        
        Geographic regions for climate data.

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier (lowercase)
      placeholder: "e.g. global"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Display name
      placeholder: "e.g. Global"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the region
