name: "Add/Modify: Source Type"
description: Add or modify a source type in WCRP Universe
title: "Add/Modify: Source Type"
labels: ['delta', 'source-type', 'Review', 'keep-open']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Source Type

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier (lowercase)
      placeholder: "e.g. aogcm"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. AOGCM"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: collaborators
    attributes:
      label: Additional Collaborators
      description: |
        To add attribution to additional members include their GitHub usernames (only) separated by a comma.
      placeholder: "e.g. user1"
