name: "Add/Modify: Truncation Method"
description: Add or modify a truncation method in WCRP Universe
title: "Add/Modify: Truncation Method: <Type name here>"
labels: ['delta', 'truncation_method', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Add/Modify: Truncation Method
        
        Spectral truncation methods.

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier (lowercase)
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Display name

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
