name: "Add/Modify: Units"
description: Add or modify a unit definition in WCRP Universe
title: "Add/Modify: Units"
labels: ['delta', 'units', 'Review', 'keep-open']
body:
  - type: markdown
    attributes:
      value: |
        ## Add/Modify: Units
        
        Unit definitions for climate data.

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier (lowercase)
      placeholder: "e.g. m"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Display name
      placeholder: "e.g. meters"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: collaborators
    attributes:
      label: Additional Collaborators
      description: |
        To add attribution to additional members include their GitHub usernames (only) separated by a comma.
      placeholder: "e.g. user1"
